services/ml/compilation_impl_mac.h, services/ml/compilation_impl_mac.mm, services/ml/execution_impl_mac.mm
Fix https://github.com/intel/webml-polyfill/issues/22 and https://github.com/intel/webml-polyfill/issues/23
=> Squeezenet

services/ml/compilation_impl_mac.h, services/ml/compilation_impl_mac.mm, services/ml/execution_impl_mac.mm, services/ml/mpscnn_context.mm
Fix https://github.com/intel/webml-polyfill/issues/45 and https://github.com/intel/webml-polyfill/issues/46
=> Support multiple outputs and RELU1/RELU6 in MPS backend

content/browser/service_manager/service_manager_context.cc, content/gpu/gpu_service_factory.cc
The patch has passed test cases and benchmarks on Android and Mac, the results are the same as before. 
bug = https://github.com/intel/webml-polyfill/issues/38
=> Move ml service from browser to gpu process

services/ml/compilation_impl_mac.mm
@sunlin-link , thanks for your catch. Please help to review.
=> Fix bug which caused compile error in debug build

services/ml/compilation_impl_mac.mm, services/ml/execution_impl_mac.mm, services/ml/model_impl_mac.mm
@huningxin , please help to review.
=> Add batch apply filter and check the result of creating layer

services/ml/compilation_impl_mac.mm
Fix [intel/webml-polyfill#158](https://github.com/intel/webml-polyfill/issues/158)
=> remove debug log in release build

third_party/blink/renderer/modules/ml/compilation.cpp, third_party/blink/renderer/modules/ml/compilation.h, third_party/blink/renderer/modules/ml/execution.cpp, third_party/blink/renderer/modules/ml/execution.h, third_party/blink/renderer/modules/ml/ml.cpp, third_party/blink/renderer/modules/ml/ml.h, third_party/blink/renderer/modules/ml/model.cpp, third_party/blink/renderer/modules/ml/model.h, third_party/blink/renderer/modules/ml/navigator_ml.cpp, third_party/blink/renderer/modules/ml/navigator_ml.h, third_party/blink/renderer/modules/ml/neural_network_context.cpp, third_party/blink/renderer/modules/ml/neural_network_context.h
1, Function declaration order should match function definition order.
2, Items local to a .cc file should be wrapped in an unnamed namespace.
3, Use "git cl lint" to check more rules.
Fix https://github.com/intel/webml-polyfill/issues/96
=> Coding style for blink implementation

services/ml/BUILD.gn
Fix https://github.com/intel/webml-polyfill/issues/175
=> [Win] Fix build failure due to clDNN64.pdb

services/ml/compilation_impl_mac.mm, services/ml/execution_impl_mac.mm
Fixes [intel/webml-polyfill#152](https://github.com/intel/webml-polyfill/issues/152)
@fujunwei @huningxin  Please help to review.
=> Add batch support for softmax operation

third_party/blink/renderer/modules/ml/model.cpp
Fixes:
https://github.com/intel/webml-polyfill/issues/77
https://github.com/intel/webml-polyfill/issues/89
https://github.com/intel/webml-polyfill/issues/174
which is regression by
https://github.com/otcshare/chromium-src/pull/20
=> Check model_info_ instead of is_finished_

services/ml/BUILD.gn, services/ml/cl_dnn_symbol_table.cc, services/ml/cl_dnn_symbol_table.h, services/ml/compilation_impl_cl_dnn.cc, services/ml/execution_impl_cl_dnn.cc, services/ml/execution_impl_cl_dnn.h, services/ml/late_binding_symbol_table.cc, services/ml/late_binding_symbol_table.h, services/ml/model_impl_cl_dnn.cc, services/ml/model_impl_cl_dnn.h, services/ml/neural_network_impl_cl_dnn.cc, services/ml/public/interfaces/neuralnetwork.mojom
Fix https://github.com/intel/webml-polyfill/issues/180
=> Load dynamically clDNN with dlopen

services/ml/compilation_impl_mac.h, services/ml/compilation_impl_mac.mm, services/ml/execution_impl_mac.h, services/ml/execution_impl_mac.mm
fix https://github.com/intel/webml-polyfill/issues/92 and https://github.com/intel/webml-polyfill/issues/117
=> Support ADD and MUL op in MPS

services/ml/model_impl_cl_dnn.cc
Fix https://github.com/intel/webml-polyfill/issues/230
Fix https://github.com/intel/webml-polyfill/issues/231
=> [clDNN] fix results of ADD and MUL ops

base/mac/sdk_forward_declarations.h, services/ml/compilation_impl_mac.mm
fix https://github.com/intel/webml-polyfill/issues/250.
=> Forward declarations MPSCNNAdd/MPSCNNMultiply

services/ml/compilation_impl_mac.mm
Fix https://github.com/intel/webml-polyfill/issues/255
=> [MPS] Fix the concatenation failure for inception v3

services/ml/execution_impl_mac.h, services/ml/execution_impl_mac.mm
Fix https://github.com/intel/webml-polyfill/issues/258
=> [BNNS] fix createExecution failure

services/ml/compilation_impl_mac.h, services/ml/compilation_impl_mac.mm, services/ml/execution_impl_mac.mm
Fixes [intel/webml-polyfill#161](https://github.com/intel/webml-polyfill/issues/161)
@fujunwei @huningxin Please help to review.
=> Fix concatenation batch operation

services/ml/compilation_impl_mac.mm, services/ml/execution_impl_mac.h, services/ml/execution_impl_mac.mm
Fix [intel/webml-polyfill#147](https://github.com/intel/webml-polyfill/issues/147)
@fujunwei Please help to review.
=> Fix the crash issue when running cts tests for bnns backend

services/ml/compilation_impl_mac.mm
Fix [intel/webml-polyfill#294](https://github.com/intel/webml-polyfill/issues/294)
=> Fix the alpha value for RELU1 activation function

third_party/blink/renderer/modules/ml/model.cpp
fix https://github.com/intel/webml-polyfill/issues/67.
=> Raise error when setting a Array data which length > 1 for a scalar

services/ml/common.cc, services/ml/common.h, services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_mps.h, services/ml/compilation_impl_mac_mps.mm
fix https://github.com/intel/webml-polyfill/issues/224.
=> [MPS] Support Fully Connected operation

services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_bnns.h, services/ml/compilation_impl_mac_bnns.mm, services/ml/compilation_impl_mac_mps.mm, services/ml/execution_impl_mac_bnns.mm, services/ml/ml_utils_mac.h, services/ml/ml_utils_mac.mm
Fix[ intel/web-polyfill#225](https://github.com/intel/webml-polyfill/issues/225)
Total 11 CTS, pass 11, fail 0.
=> implement of FullyConnected layer for BNNS backend

services/ml/cl_dnn_symbol_table.h, services/ml/model_impl_cl_dnn.cc
fix https://github.com/intel/webml-polyfill/issues/344
=> [clDNN] fix Linux build failure

base/mac/sdk_forward_declarations.h, services/ml/BUILD.gn, services/ml/compilation_impl_mac.h, services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_bnns.mm, services/ml/compilation_impl_mac_mps.h, services/ml/compilation_impl_mac_mps.mm, services/ml/execution_impl_mac_mps.h, services/ml/execution_impl_mac_mps.mm, services/ml/ml_utils_mac.h, services/ml/mps_protocols_impl.h, services/ml/mps_protocols_impl.mm
fix https://github.com/intel/webml-polyfill/issues/210.
=> Mps nn graph

services/ml/model_impl_cl_dnn.cc, services/ml/public/interfaces/constants.mojom, third_party/blink/renderer/modules/ml/neural_network_context.h, third_party/blink/renderer/modules/ml/neural_network_context.idl
Fix https://github.com/intel/webml-polyfill/issues/361
=> [clDNN] implement ATROUS_CONV_2D and ATROUS_DEPTHWISE_CONV_2D

services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_bnns.h, services/ml/compilation_impl_mac_bnns.mm, services/ml/execution_impl_mac_bnns.mm, services/ml/ml_utils_mac.h
Fix [intel/webpolyfill#357](https://github.com/intel/webml-polyfill/issues/357)
Fix [intel/webpolyfill#321](https://github.com/intel/webml-polyfill/issues/321)
I implement add operation in this PR, but it doesn't support broadcasting by now.
I have tried some ways to support broadcasting, but it all failed. I think we can create a new issue to track it after this PR is merged.
And ResNet50 V1 and V2 can work on bnns backend after this PR is merged. 
ResNet50 V1 costs about 70ms and ResNet50V2 costs 90ms.
@fujunwei  Please help to review.
=> [BNNS]Implement add operation

services/ml/compilation_impl_mac_bnns.mm
Fix [intel/web-polyfill#396](https://github.com/intel/webml-polyfill/issues/396)
@fujunwei Please help to review.
=> Fix crash issue after add operation implement.

chrome/installer/linux/common/installer.include
fix https://github.com/intel/webml-polyfill/issues/418
=> [Linux] add libclDNN64.so into deb installer

services/ml/compilation_impl_mac_bnns.mm
Fix [intel/web-polyfill#448](https://github.com/intel/webml-polyfill/issues/448)
@fujunwei , Please help to review.
=> [BNNS]Fix ResNet50 examples issue

base/mac/sdk_forward_declarations.h, services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_mps.h, services/ml/compilation_impl_mac_mps.mm
fix https://github.com/intel/webml-polyfill/issues/339.
=> [MPS] implement resize bilinear operation

services/ml/execution_impl_mac_bnns.mm
Fix [intel/web-polyfill#435](https://github.com/intel/webml-polyfill/issues/435).
This issue was caused by a bug in concatenation operation.
@fujunwei , please help to review.
=> [BNNS]Fix issue for running inception v3/v4 model

services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_mps.h, services/ml/compilation_impl_mac_mps.mm
fix https://github.com/intel/webml-polyfill/issues/360
=> [MPS] Support dilated Deeplab

services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_bnns.h, services/ml/compilation_impl_mac_bnns.mm, services/ml/execution_impl_mac_bnns.mm, services/ml/ml_utils_mac.h
Fix [intel/webml-polyfill#322](https://github.com/intel/webml-polyfill/issues/322)
@fujunwei , please help to review.
=> [BNNS]Implementation of mul

services/ml/cl_dnn_custom_kernels.cc, services/ml/compilation_delegate_cl_dnn.cc, services/ml/compilation_impl.cc, services/ml/compilation_impl.h
fix https://github.com/intel/webml-polyfill/issues/466
=> [clDNN] support align_corners of RESIZE_BILINEAR

services/ml/compilation_impl_mac_mps.mm
fix https://github.com/intel/webml-polyfill/issues/467.
=> [MPS] Support align_corners of RESIZE_BILINEAR

services/ml/model_impl_android.cc
Fix https://github.com/intel/webml-polyfill/issues/468
=> [NNAPI] discard align_corners

services/ml/compilation_delegate_cl_dnn.cc, services/ml/compilation_delegate_mkl_dnn.cc, services/ml/compilation_impl.cc, services/ml/execution_impl_cl_dnn.cc, services/ml/execution_impl_mkl_dnn.cc
=> [clDNN][MKLDNN] log errors in release build

services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_mps.h, services/ml/compilation_impl_mac_mps.mm
fix https://github.com/intel/webml-polyfill/issues/318.
=> [MPS] Different batch size for arithmetic operation isn't supported.

services/ml/compilation_delegate_mkl_dnn.cc, services/ml/compilation_delegate_mkl_dnn.h, services/ml/mkl_dnn_symbol_table.h
fix https://github.com/intel/webml-polyfill/issues/453
=> [MKLDNN] add depthwise conv2d

services/ml/compilation_delegate_mkl_dnn.cc, services/ml/mkl_dnn_symbol_table.h
fix https://github.com/intel/webml-polyfill/issues/454
=> [MKLDNN] implement atrous convolutions

services/ml/compilation_delegate_mkl_dnn.cc, services/ml/compilation_delegate_mkl_dnn.h, services/ml/mkl_dnn_symbol_table.h
fix https://github.com/intel/webml-polyfill/issues/458
=> [MKLDNN] implement softmax

services/ml/compilation_delegate_mkl_dnn.cc, services/ml/compilation_delegate_mkl_dnn.h, services/ml/execution_impl_mkl_dnn.cc, services/ml/execution_impl_mkl_dnn.h
fix https://github.com/intel/webml-polyfill/issues/459
=> [MKLDNN] implement reshape

services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_bnns.h, services/ml/compilation_impl_mac_bnns.mm, services/ml/execution_impl_mac_bnns.mm, services/ml/ml_utils_mac.h
Fix [intel/webml-polyfill#340](https://github.com/intel/webml-polyfill/issues/340).
@fujunwei , please help to review.
=> [BNNS]Implement of resize_bilinear.

services/ml/compilation_impl.cc
fix https://github.com/intel/webml-polyfill/issues/551
=> [MKLDNN] fix padding calculation with dilation

services/ml/compilation_delegate_mkl_dnn.cc, services/ml/mkl_dnn_symbol_table.h
fix https://github.com/intel/webml-polyfill/issues/456
=> [MKLDNN] implement ADD operation

services/ml/compilation_delegate_mkl_dnn.cc, services/ml/compilation_delegate_mkl_dnn.h, services/ml/mkl_dnn_symbol_table.h
fix https://github.com/intel/webml-polyfill/issues/460
=> [MKLDNN] implement FULLY_CONNECTED op

services/ml/compilation_delegate_mkl_dnn.cc, services/ml/mkl_dnn_symbol_table.h
fix https://github.com/intel/webml-polyfill/issues/457
=> [MKLDNN] implement CONCATENATION op

services/ml/compilation_delegate_cl_dnn.cc
Fix [intel/webml-polyfill#277](https://github.com/intel/webml-polyfill/issues/277).
@fujunwei , please help to review.
=> [cldnn]Fix a value for Relu1 activation function

services/ml/compilation_impl_mac_bnns.mm, services/ml/execution_impl_mac_bnns.mm, services/ml/ml_utils_mac.h
Fix [webml-polyfill#664](https://github.com/intel/webml-polyfill/issues/664)
-  Squeezenet(onnx) in eager - PASS
- Inception ResnetV2 in eager - PASS
- ResNet V1 in eager - PASS
- Resnet V2 in eager - PASS
- Squeezenet(TFLite) in eager - PASS
=> [BNNS]Fix crash issue for eager model

third_party/blink/renderer/modules/ml/neural_network_context.h, third_party/blink/renderer/modules/ml/neural_network_context.idl
Fix [intel/webml-polyfill#651](https://github.com/intel/webml-polyfill/issues/651).
@fujunwei Please help to review.
=> [cldnn]Fix crash issue for MAXIMUM/TRANSPOSE/BATCH_TO_SPACE_ND ops

services/ml/compilation_delegate_ie.cc
fix https://github.com/intel/webml-polyfill/issues/698
=> [IE] support DEPTHWISE_CONV_2D

services/ml/compilation_impl_mac_bnns.mm
Fix [intel/webml-polyfill#680](https://github.com/intel/webml-polyfill/issues/680)
@fujunwei Please help to review.
=> [BNNS]Add input size check for convolution

services/ml/compilation_delegate_ie.cc
fix https://github.com/intel/webml-polyfill/issues/699
=> [IE] support AVERAGE_POOL_2D and MAX_POOL_2D

services/ml/compilation_delegate_ie.cc
fix https://github.com/intel/webml-polyfill/issues/701
=> [IE] support SOFTMAX

services/ml/compilation_delegate_ie.cc
fix https://github.com/intel/webml-polyfill/issues/702
=> [IE] implement RESHAPE

services/ml/compilation_delegate_ie.cc
fix https://github.com/intel/webml-polyfill/issues/700 and https://github.com/intel/webml-polyfill/issues/703
=> [IE] implement CONCATENATION and FULLY_CONNECTED

services/ml/compilation_impl_mac_bnns.mm, services/ml/execution_impl_mac_bnns.mm
Fix [intel/webml-polyfill#718](https://github.com/intel/webml-polyfill/issues/718)
@fujunwei Please help to review. Thanks！
=> [bnns]Fix the crash issue when running hybrid model

services/ml/BUILD.gn
fix https://github.com/intel/webml-polyfill/issues/745
=> [IE] fix ie build by depending on mojom

content/browser/gpu/gpu_process_host.cc, services/ml/BUILD.gn, services/ml/compilation_delegate_dml.cc, services/ml/compilation_delegate_dml.h, services/ml/compilation_impl.cc, services/ml/direct_ml.h, services/ml/dml_d3dx12_utils.h, services/ml/dml_symbol_table.cc, services/ml/dml_symbol_table.h, services/ml/execution_impl_dml.cc, services/ml/execution_impl_dml.h, services/ml/late_binding_symbol_table.cc, services/ml/ml_switches.cc, services/ml/ml_switches.h, services/ml/ml_utils_dml.cc, services/ml/ml_utils_dml.h, services/ml/public/cpp/BUILD.gn
=> [DML] Implement an operation of adding with DirectML backend

services/ml/compilation_delegate_dml.cc, services/ml/compilation_delegate_dml.h, services/ml/execution_impl_dml.cc, services/ml/ml_utils_dml.cc, services/ml/ml_utils_dml.h
=> [DML] Implement Activation and max/average Pooling

services/ml/compilation_delegate_dml.cc
Chromium version: b5692cd
Webml-polyfill version: 853173e
PR Submission Proposal:
    ➤   Win-WebNN-Sustained-DML: OK
PR Submission Message:
Total Test Cases: 714
Pass to Fail: 0
Fail to Pass: 116
Fix https://github.com/intel/webml-polyfill/issues/820
=> [DML] Adapt the latest graphic driver

services/ml/compilation_impl_mac.mm, services/ml/compilation_impl_mac_bnns.h, services/ml/compilation_impl_mac_bnns.mm, services/ml/execution_impl_mac_bnns.mm, services/ml/ml_utils_mac.h
Fix [intel/webml-polyfill#732](https://github.com/intel/webml-polyfill/issues/732). 
- cts-test: run normally
- squeenet: run well
- mobilenet v1: run well in hybrid mode
=> [BNNS]Fix the issue for ADD/MUL/CONCATENATION

content/browser/gpu/gpu_process_host.cc
Fix [intel/webml-polyfill#845](https://github.com/intel/webml-polyfill/issues/845).
@fujunwei Please help to review. Thanks!
=> Fix the nightly build failing

services/ml/late_binding_symbol_table.cc
Fix[ intel/webml-polyfill#846](https://github.com/intel/webml-polyfill/issues/846).
@fujunwei Please help to review. Thanks!
=> [Linux & Windows]fix nightly build failed

services/ml/mkl_dnn_symbol_table.cc
@fujunwei , Please help to review. Thanks!
=> [linux]Fix nightly build failed
